# Generated by Django 6.1.1 on 2026-09-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=10, null=True, verbose_name='性别')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('appointment_time', models.TimeField(blank=True, null=True, verbose_name='预约时间')),
                ('consultation_type', models.CharField(choices=[('线上', '线上视频/电话'), ('线下', '线下面谈')], default='线上', max_length=20, verbose_name='咨询方式')),
                ('preferred_lawyer', models.CharField(blank=True, max_length=50, null=True, verbose_name='指定律师')),
                ('case_category', models.CharField(choices=[('民事纠纷', '民事纠纷'), ('刑事辩护', '刑事辩护'), ('婚姻家事', '婚姻家事'), ('合同纠纷', '合同纠纷'), ('劳动争议', '劳动争议'), ('知识产权', '知识产权'), ('公司法务', '公司法务'), ('房产纠纷', '房产纠纷'), ('交通事故', '交通事故'), ('其他', '其他')], default='其他', max_length=50, verbose_name='案件类别')),
                ('case_description', models.TextField(blank=True, null=True, verbose_name='案件描述')),
                ('urgency_level', models.CharField(choices=[('一般', '一般'), ('较急', '较急'), ('紧急', '紧急')], default='一般', max_length=10, verbose_name='紧急程度')),
                ('status', models.CharField(choices=[('待确认', '待确认'), ('已确认', '已确认'), ('已完成', '已完成'), ('已取消', '已取消')], default='待确认', max_length=20, verbose_name='处理状态')),
                ('assigned_lawyer', models.CharField(blank=True, max_length=50, null=True, verbose_name='分配律师')),
                ('admin_remark', models.TextField(blank=True, null=True, verbose_name='后台备注')),
                ('source', models.CharField(choices=[('官网', '官网表单'), ('微信小程序', '微信小程序'), ('电话咨询', '电话咨询'), ('其他', '其他')], default='官网', max_length=30, verbose_name='预约来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户预约咨询信息',
                'verbose_name_plural': '客户预约咨询信息表',
                'db_table': 'customer_consultation',
                'ordering': ['-created_at'],
            },
        ),
    ]
