# Generated by Django 6.1.1 on 2026-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerconsultation',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='customerconsultation',
            name='assigned_lawyer',
        ),
        migrations.RemoveField(
            model_name='customerconsultation',
            name='consultation_type',
        ),
        migrations.RemoveField(
            model_name='customerconsultation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerconsultation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customerconsultation',
            name='preferred_lawyer',
        ),
        migrations.AddField(
            model_name='customerconsultation',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='customerconsultation',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='admin_remark',
            field=models.TextField(blank=True, default='', verbose_name='后台备注'),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='期望预约日期'),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='case_category',
            field=models.CharField(choices=[('公司治理', '公司治理'), ('私募股权投融资', '私募股权投融资'), ('国资交易', '国资交易'), ('基金合规', '基金管理人募投管退全流程合规法律服务'), ('交易架构设计', '交易架构设计'), ('保险资管', '保险资管'), ('合同纠纷', '合同纠纷'), ('侵权纠纷', '侵权纠纷'), ('劳动争议', '劳动争议'), ('公司股权纠纷', '公司股权纠纷'), ('金融借款纠纷', '金融借款纠纷'), ('建设工程纠纷', '建设工程纠纷'), ('知识产权纠纷', '知识产权纠纷'), ('不正当竞争纠纷', '不正当竞争纠纷'), ('其他', '其他')], default='其他', max_length=50, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='case_description',
            field=models.TextField(blank=True, default='', verbose_name='诉求简述'),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='urgency_level',
            field=models.CharField(choices=[('一般', '一般'), ('紧急', '紧急')], default='一般', max_length=10, verbose_name='紧急程度'),
        ),
    ]
