# Generated by Django 6.1.1 on 2026-09-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0002_remove_customerconsultation_appointment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='案例标题')),
                ('role', models.CharField(max_length=200, verbose_name='律师角色')),
                ('amount', models.CharField(blank=True, default='', max_length=50, verbose_name='金额标签')),
                ('description', models.TextField(blank=True, default='', verbose_name='案例描述')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代表案例',
                'verbose_name_plural': '代表案例表',
                'db_table': 'representative_case',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Logo图片')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务客户',
                'verbose_name_plural': '服务客户Logo墙表',
                'db_table': 'service_client',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
