# Generated by Django 6.1 on 2026-09-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0003_representativecase_serviceclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='业务名称')),
                ('category', models.CharField(choices=[('non_litigation', '非诉业务'), ('litigation', '诉讼业务')], default='non_litigation', max_length=20, verbose_name='业务分类')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务领域',
                'verbose_name_plural': '业务领域表',
                'db_table': 'practice_area',
                'ordering': ['category', 'sort_order', '-created_at'],
            },
        ),
    ]
