# Generated by Django 6.1 on 2026-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0004_practicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerconsultation',
            name='appointment_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='期望预约日期'),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='status',
            field=models.CharField(choices=[('待确认', '待确认'), ('已确认', '已确认'), ('已完成', '已完成'), ('已取消', '已取消')], db_index=True, default='待确认', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logos/', verbose_name='Logo图片'),
        ),
    ]
