"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# ===== Django 6.1 + SimpleUI 兼容性补丁 =====
# Django 6.1 引入了 ActionLocation 枚举，SimpleUI 序列化时无法处理
# 通过 monkey-patch json.JSONEncoder.default 使其支持 Enum 序列化
import json
import enum

_original_encoder_default = json.JSONEncoder.default

def _patched_encoder_default(self, o):
    if isinstance(o, enum.Enum):
        return o.value
    return _original_encoder_default(self, o)

json.JSONEncoder.default = _patched_encoder_default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从 .env 文件读取，不再硬编码在代码中
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'lawyer_app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


def _parse_database_url(url: str, base_dir: Path) -> dict:
    """解析 DATABASE_URL 环境变量，支持 SQLite 和 PostgreSQL"""
    if url.startswith('sqlite'):
        db_name = url.replace('sqlite:///', '')
        if not db_name.startswith('/'):
            db_name = str(base_dir / db_name)
        return {'ENGINE': 'django.db.backends.sqlite3', 'NAME': db_name}
    elif url.startswith('postgresql') or url.startswith('postgres'):
        from urllib.parse import urlparse
        parsed = urlparse(url)
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/'),
            'USER': parsed.username or '',
            'Password': parsed.PASSWORD or '',
            'HOST': parsed.hostname or 'localhost',
            'PORT': str(parsed.port or 5432),
        }
    raise ValueError(f'不支持的数据库 URL: {url}')


DATABASES = {
    'default': config(
        'DATABASE_URL',
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        cast=lambda url: _parse_database_url(url, BASE_DIR),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# 媒体文件（用户上传的图片等）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Email — 开发环境使用 console 后端（邮件输出到终端）
# 生产环境切换为 SMTP：'django.core.mail.backends.smtp.EmailBackend'
# 并配置 EMAIL_HOST / EMAIL_PORT / EMAIL_HOST_USER / EMAIL_HOST_PASSWORD
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ===== CORS 跨域配置 =====
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv(),
)

# ===== Django REST Framework 配置 =====
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    # 限流配置：防止 API 被恶意刷请求
    'DEFAULT_THROTTLE_RATES': {
        'consultation': '5/min',   # 预约接口：每分钟最多5次
    },
}

# ===== SimpleUI 配置 =====
SIMPLEUI_HOME_INFO = False
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

# 关闭多标签页模式，点击菜单直接跳转页面
SIMPLEUI_CONFIG = {
    'system_keep': True,
}
SIMPLEUI_ANALYSIS = False

# ===== 安全响应头配置 =====
# 以下配置在所有环境下生效
SECURE_BROWSER_XSS_FILTER = True          # 启用浏览器 XSS 过滤
SECURE_CONTENT_TYPE_NOSNIFF = True        # 禁止浏览器 MIME 类型嗅探
X_FRAME_OPTIONS = 'SAMEORIGIN'             # 允许同源 iframe（SimpleUI 需要）
SESSION_COOKIE_HTTPONLY = True             # JS 无法读取 Session Cookie
CSRF_COOKIE_HTTPONLY = False               # SPA 前端需要读取 CSRF Cookie

# 以下配置仅在 HTTPS 生产环境下生效（DEBUG=False 时启用）
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000         # HSTS 有效期一年
    SECURE_SSL_REDIRECT = True             # HTTP 自动跳转 HTTPS
    SESSION_COOKIE_SECURE = True           # Session Cookie 仅通过 HTTPS 传输
    CSRF_COOKIE_SECURE = True              # CSRF Cookie 仅通过 HTTPS 传输

# ===== 日志配置 =====
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        # API 请求日志（预约提交、限流触发等）
        'api_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'api.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # 安全事件日志（登录失败、异常访问等）
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'security.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # 服务器错误日志
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'error.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Django 安全相关（登录失败、CSRF 拒绝等）
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django 请求错误
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # 业务应用日志（预约咨询等）
        'lawyer_app': {
            'handlers': ['api_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
